### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by vassyz** [StephenHynes7/le_utils#19]
I don't really want my whole team to get the log emails. Why is this feature so hard to implement? Anyway, this script doesn't work for me.

    $ python le_alert-email-change.py XXXX gbanners-api-qa vasile.zaremba@isobar.com
    Traceback (most recent call last):
      File "le_alert-email-change.py", line 76, in <module>
        setup()
      File "le_alert-email-change.py", line 14, in setup
        get_hosts()
      File "le_alert-email-change.py", line 22, in get_hosts
        response = urllib2.urlopen(url).read()
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
        response = meth(req, response)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
        return self._call_chain(*args)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by StephenHynes7** [comment]
Try

'python le_alert-email-change.py 04a24fc2-ac77-4b57-8326-4aec7da4a85b Heroku vasile.zaremba@isobar.com'

**Comment by vassyz** [comment]
Thanks for that, I copied one line too many from the console. Sorry, busy day at work.
It works now.

**Comment by StephenHynes7** [comment]
No worries I completely understand :)

**Comment by vassyz** [comment]
Sorry, just noticed you've also got my email in your comment, could you please put a dummy one instead? Thanks.
